version: '3'
services:
  localstack:
    image: localstack/localstack:0.8.7
    environment:
      - SERVICES=sqs:4576

  php70:
    image: php:7.0-cli
    command: tail -f /dev/null
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - localstack

  php71:
    image: php:7.1-cli
    command: tail -f /dev/null
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - localstack

  php72:
    image: php:7.2-cli
    command: tail -f /dev/null
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - localstack

  netcat:
    image: appropriate/nc
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - localstack
    command: tail -f /dev/null

  awscli:
    image: garland/aws-cli-docker:1.15.47
    depends_on:
      - localstack
    command: tail -f /dev/null
